spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    listener:
      auto-startup: true

jwt:
  secret: ${JWT_SECRET}

app:
  security:
    internal-api-key: ${INTERNAL_API_KEY}
  services:
    wallet-url: http://localhost:8088/api/v1/wallets

logging:
  level:
    root: WARN
    com.paypal: INFO
